---
  - name: installing and launching metribeat
    hosts: webservers
    become: yes
    tasks:

#download the .deb file from artifacts.elastic.com
    - name: download metribeat deb
      command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.6.1-amd64.deb

#Install .deb file using the dpkg command
    - name: install metribeat deb
      command: sudo dpkg -i metricbeat-7.6.1-amd64.deb

#enable and configure system module
    - name: enable and configure system module
      command: metricbeat modules enable docker

#copy the yml file to the destination
    - name: drop in metricbeat.yml
      copy:
        src: /etc/ansible/files/metricbeat-config.yml
        dest: /etc/metricbeat/metricbeat.yml

    - name: enable and configure system module
      command: metricbeat modules enable docker

    - name: setup metricbeat
      command: metricbeat setup

    - name: startup metricbeat
      command: service metricbeat start

    - name: enable service metricbeat on boot
      systemd:
        name: metricbeat
        enabled: yes
